Numpy: Numeric Computing library

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
# Accessing the elements in an numpy array
a[0], a[1]
b[2], b[4]

(1.0, 2.0)

In [8]:
a[1:3]

array([2, 3])

In [10]:
b[3:4]

array([1.5])

In [11]:
b[::2]

array([0., 1., 2.])

In [12]:
b[0], b[1],b[-1]

(0.0, 0.5, 2.0)

In [13]:
### Multi index selection. OUTPUT WILL BE Array
b[[0,2,-1]]

array([0., 1., 2.])

Array Types

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [19]:
## create an array with float data type
np.array([1,2,3,4], dtype = float)

array([1., 2., 3., 4.])

In [22]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
## Numpy can handle integers, float, boolean, dates
## Numpy can store strings and other objects. But not efficient since numpy is for numeric processing.

Dimensions

In [24]:
## Two dimensional Arrays

A = np.array([
    [1,2,3],
    [4,5,6]
])

In [28]:
# Shape - Number of rows and columns
A.shape

(2, 3)

In [26]:
# Size- Total number of elements
A.size

6

In [29]:
### ndim -- Provides dimenstion of the array. Either 2D and 3D.
A.ndim

2

Indexing and slicing the Matrix

In [30]:
A = np.array([
#    0 1 2   
    [1,2,3], # 0
    [4,5,6], # 1
    [7,8,9]  # 2
])

In [32]:
# SELECT Element 4 from the matrix
A[1,0]

# SELECT Element 8 from the matrix
A[2,1]

8

In [33]:
### Multi-indexing 
### Row slicing and Column slicinb
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [35]:
### Select 5,6,8,9 from the matrix

A[1:, 1:]

array([[5, 6],
       [8, 9]])

Summary Statistics

In [36]:
a = np.array([1,2,3,4])


In [39]:
a.sum()
a.mean()
a.var()

1.25

In [40]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [41]:
A.sum()

45

In [42]:
A.mean()

5.0

In [43]:
A.std()

2.581988897471611

In [44]:
### Add the row values.
A.sum(axis =0)

array([12, 15, 18])

In [45]:
### Add the column values
A.sum(axis=1)

array([ 6, 15, 24])

Broadcasting and Vectorized Operations

In [48]:
#### Works with Boolean
a = np.arange(4)

In [49]:
a

array([0, 1, 2, 3])

In [50]:
### +10 will be added to each element
a + 10

array([10, 11, 12, 13])

In [51]:
### Will be multiplied to each element
a * 10

array([ 0, 10, 20, 30])

In [56]:
a

array([110, 111, 112, 113])

In [53]:
a += 100

In [54]:
### Numpy will not modify the existing array rather creates new array

In [55]:
a

array([110, 111, 112, 113])

In [57]:
### List comprehension in Numpy
l =[0,1,2,3]
[i*10 for i in l]


[0, 10, 20, 30]

In [59]:
### We can add array and array
a = np.arange(4)
b = np.array([10,10,10,10])


In [60]:
a + b

array([10, 11, 12, 13])

In [61]:
a * b

array([ 0, 10, 20, 30])

Boolean Arrays

In [62]:
a = np.arange(4)

In [63]:
a[[0, -1]]

array([0, 3])

In [65]:
a[[True, False, False, True]]

array([0, 3])

In [66]:
a >= 2

array([False, False,  True,  True])

In [67]:
a >= 2

array([False, False,  True,  True])

In [68]:
a[a >= 2]

array([2, 3])

In [69]:
a.mean()

1.5

In [70]:
a[a > a.mean()]

array([2, 3])

In [71]:
a[~(a > a.mean())]

array([0, 1])

In [72]:
### Or and And operation

a[(a == 0) | (a == 1)]

array([0, 1])

In [73]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [74]:
A = np.random.randint(100, size=(3,3))

In [75]:
A

array([[83, 61, 85],
       [15, 35, 27],
       [76, 56, 11]])

In [76]:
A > 30

array([[ True,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [77]:
A[A>30]

array([83, 61, 85, 35, 76, 56])

In [78]:
A[(A >= 50) & (A <= 75)]

array([61, 56])

Linear Algebra

In [79]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [80]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [81]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [82]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [83]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

In [85]:
# An integer in Python is > 34 bytes
import sys
sys.getsizeof(1)

28

In [86]:
## Longs are even larger
sys.getsizeof(10**100)

72

In [89]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [90]:
np.dtype(np.int8).itemsize

1

In [91]:
np.dtype(float).itemsize

8

Lists are even larger

In [92]:
sys.getsizeof([1])

64

In [93]:
np.array([1]).nbytes

4

And Performance is also important

In [94]:
l = list(range(1000))

In [95]:
a = np.arange(1000)

In [106]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1.64 ms


332833500

In [107]:
%time sum([x**2 for x in l])

CPU times: total: 0 ns
Wall time: 1.52 ms


332833500

Useful Numpy Functions

### Random

In [108]:
np.random.random(size = 2)

array([0.16935463, 0.54749154])

In [109]:
np.random.normal(size=2)

array([-1.43642484,  0.94262992])

In [110]:
np.random.rand(2,4)

array([[0.75634492, 0.48734888, 0.4306024 , 0.26439418],
       [0.08215473, 0.97387364, 0.33220178, 0.92657535]])

### arange

In [111]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [113]:
np.arange(0,1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [114]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### linspace

In [116]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [117]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [118]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [119]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [121]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [122]:
np.empty(5)

array([1., 1., 1., 1., 1.])

### identity and eye

In [123]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])